#!/usr/bin/env python3
"""
Tests for pptx-content-extractor skill
Test 1: Generate 100-word summary (proves skill can see content)
Test 2: Modify content (proves skill can clean/edit content)
Test 3: Output a PPTX file (proves skill can generate files)
"""

import sys
import io
import os
import re
import requests
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

API_URL = os.getenv("PPTX_EXTRACTION_API_URL", "http://127.0.0.1:8000")
OUTPUT_DIR = Path(__file__).parent / "test_output"
OUTPUT_DIR.mkdir(exist_ok=True)


def get_content(pptx_path: str) -> str:
    """Call API to get PPTX content."""
    with open(pptx_path, "rb") as f:
        r = requests.post(f"{API_URL}/extract-pptx", files={"file": f}, timeout=60)
    data = r.json()
    assert data["status"] == "success", f"API error: {data.get('message')}"
    return data["content"]


def test1_summarize(content: str) -> str:
    """Test 1: Ask Claude to produce a 100-word summary."""
    from anthropic import Anthropic
    client = Anthropic()
    msg = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=300,
        messages=[{
            "role": "user",
            "content": f"Summarize the following presentation in exactly 100 words:\n\n{content[:8000]}"
        }]
    )
    summary = msg.content[0].text
    word_count = len(summary.split())
    assert word_count >= 80, f"Summary too short: {word_count} words"
    return summary


def test2_modify(content: str) -> str:
    """Test 2: Clean content - keep only slide titles (first line of each slide)."""
    lines = content.split("\n")
    titles = [line for line in lines if line.startswith("Slide ")]
    cleaned = "\n".join(titles)
    assert len(cleaned) > 0, "No slide titles found"
    assert len(cleaned) < len(content), "Content was not modified"
    return cleaned


def test3_output_pptx(content: str) -> Path:
    """Test 3: Generate a PPTX file from content."""
    from pptx import Presentation
    from pptx.util import Inches, Pt

    output_file = OUTPUT_DIR / "test_output.pptx"
    prs = Presentation()

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = "PPTX Skill Test Output"
    slide.placeholders[1].text = "Generated by pptx-content-extractor"

    # Content slides (one per chunk)
    chunks = [content[i:i+300] for i in range(0, min(len(content), 900), 300)]
    for i, chunk in enumerate(chunks, 1):
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = f"Content {i}"
        slide.placeholders[1].text = chunk

    prs.save(str(output_file))
    assert output_file.exists(), "PPTX file was not created"
    assert output_file.stat().st_size > 0, "PPTX file is empty"
    return output_file


def run():
    if len(sys.argv) < 2:
        print("Usage: python run_tests.py <path_to_pptx>")
        sys.exit(1)

    pptx_path = sys.argv[1]
    passed = 0

    print(f"PPTX: {pptx_path}")
    print(f"API: {API_URL}\n")

    # Get content from API (shared across all tests)
    print("Fetching content from API...")
    content = get_content(pptx_path)
    print(f"Content retrieved: {len(content)} characters\n")

    # Test 1
    print("[TEST 1] Generate 100-word summary")
    try:
        summary = test1_summarize(content)
        print(f"  Word count: {len(summary.split())}")
        print(f"  Preview: {summary[:150]}...")
        print("  PASSED\n")
        passed += 1
    except Exception as e:
        print(f"  FAILED: {e}\n")

    # Test 2
    print("[TEST 2] Modify/clean content (extract slide titles)")
    try:
        cleaned = test2_modify(content)
        print(f"  Original length: {len(content)} chars")
        print(f"  Modified length: {len(cleaned)} chars")
        print(f"  Preview:\n{cleaned[:200]}")
        print("  PASSED\n")
        passed += 1
    except Exception as e:
        print(f"  FAILED: {e}\n")

    # Test 3
    print("[TEST 3] Output PPTX file")
    try:
        out = test3_output_pptx(content)
        print(f"  Output file: {out}")
        print(f"  File size: {out.stat().st_size} bytes")
        print("  PASSED\n")
        passed += 1
    except Exception as e:
        print(f"  FAILED: {e}\n")

    print(f"Results: {passed}/3 passed")
    sys.exit(0 if passed == 3 else 1)


if __name__ == "__main__":
    run()
